pro2 : large_new.o small.o medium_test.o


large_new.o : large_new.c
		gcc large_new.c -o large_new

small.o : small.c
		gcc small.c -o small

medium_test.o : medium_test.c
		gcc medium_test.c -o medium_test

